// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiR-f_O_stYMe48W8vL7LG9C_rf1R-YcM',
    appId: '1:958895427361:web:cb2874dda1baaf1ba47860',
    messagingSenderId: '958895427361',
    projectId: 'fmentor-73e2f',
    authDomain: 'fmentor-73e2f.firebaseapp.com',
    storageBucket: 'fmentor-73e2f.appspot.com',
    measurementId: 'G-0PXG5PD76H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgAHElh6ZK8I3HRVxZ_iG_bRj_aJbwKA',
    appId: '1:958895427361:android:60dda4edaa84afa2a47860',
    messagingSenderId: '958895427361',
    projectId: 'fmentor-73e2f',
    storageBucket: 'fmentor-73e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYa4a43crocISNzxc89caYxS305NMYl8',
    appId: '1:958895427361:ios:fdfff51b63f69322a47860',
    messagingSenderId: '958895427361',
    projectId: 'fmentor-73e2f',
    storageBucket: 'fmentor-73e2f.appspot.com',
    androidClientId: '958895427361-1ickaj07tfduvk4q71qvhsk9sbdgfchf.apps.googleusercontent.com',
    iosClientId: '958895427361-71hrgi30j0qbfhj7lf3cvgs9svt8e4qf.apps.googleusercontent.com',
    iosBundleId: 'com.fmentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYa4a43crocISNzxc89caYxS305NMYl8',
    appId: '1:958895427361:ios:fdfff51b63f69322a47860',
    messagingSenderId: '958895427361',
    projectId: 'fmentor-73e2f',
    storageBucket: 'fmentor-73e2f.appspot.com',
    androidClientId: '958895427361-1ickaj07tfduvk4q71qvhsk9sbdgfchf.apps.googleusercontent.com',
    iosClientId: '958895427361-71hrgi30j0qbfhj7lf3cvgs9svt8e4qf.apps.googleusercontent.com',
    iosBundleId: 'com.fmentor',
  );
}
